### PR TITLE
Inline bodies in class

### PR DESCRIPTION
**Pull request by ZXShady**
I also removed some explicit classes specilizations and used templates to remove them + corrected the std pointers make functions

### CODE REVIEW

**Comment by AshFungor** [comment]
@ZXShady can you elaborate how inlining helps to improve readability, or else state the reason why you propose these changes?

**Comment by ZXShady** [comment]
@AshFungor 

less lines to read. (224 vs 120)

less things to read (less namespace clutter) I had a hard time finding the function name with `hpool::_internal::blah::func` when it could have been inlined in `blah` class body and when you will have to face the double template

```
template<class T>
template<class U>
klass<T>::func(U);
```

it will get really ugly 


if you want to seperate the implementation (for extern templates purposes) I would suggest having an `.
inl` file instead of putting it inside the header

**Comment by AshFungor** [comment]
@ZXShady 

Code lines count is not a good factor to measure readability, this argument only works when applied to examples/demos.
In production code, class API should be placed tightly and easily understood from function names, this is why separating implementation from declaration is important.

If you need to jump to implementation of any methods, in VS Code press `Ctrl` and click on function/class. Also, since API can be easily observed in one place, you can do it in traditional way with `Ctrl` + `F` and search.

Ugly is relative and I can't object that.

**Comment by ZXShady** [comment]
@AshFungor 

> Code lines count is not a good factor to measure readability, this argument only works when applied to examples/demos.
In production code

well cutting down the line count in half and removing unnecessary clutter and less repition for constexpr and noexcept and having the body with the function name seems more readable to me atleast (subjective).

> easily understood from function names, this is why separating implementation from declaration is important.

I disagree no other language I see has this weird declaration and definition part only in C and C++. and the fact that this code is templated the function body can be just inlined in the class so we don't lose any benefits unlike non templated code where we suffer heavily from compilation times if we put everything in headers. infact the fact we seperate the implementation and definition in templates can hurt compile times because more things to parse.

> since API can be easily observed in one place, you can do it in traditional way with Ctrl + F and search.

I suggest doing the `.inl` file approach then it is more conventional than seperating the implementation in the headers as well.


> Ugly is relative and I can't object that.

fair, you may not find it ugly.

**Comment by AshFungor** [comment]
@ZXShady 

> I disagree no other language I see has this weird declaration and definition part only in C and C++

Yes, and in time these two acquired unique code design, which has benefits to it.

I see your point, and to be honest it all comes down to preference and style guide which is used in codebase. As you stated, inlining here indeed has no impact on compilation times.

I prefer to do it in Google's way:
https://github.com/abseil/abseil-cpp/blob/master/absl/status/statusor.h

**Comment by AshFungor** [comment]
I'll just leave this to @HyperWinX

**Comment by ZXShady** [comment]
> @ZXShady 
> 
> > I disagree no other language I see has this weird declaration and definition part only in C and C++
>
> Yes, and in time these two acquired unique code design, which has benefits to it.


I also disagree especially when modules are coming and you can just put the declaration and definition in the same file even for non templated code like normal languages.


> I see your point, and to be honest it all comes down to preference and style guide which is used in codebase. As you stated, inlining here indeed has no impact on compilation times.


I think you misunderstood me, not putting the body in the class function body can cause slower compile times because of more things to parse and name lookup.


> I prefer to do it in Google's way:
> https://github.com/abseil/abseil-cpp/blob/master/absl/status/statusor.h


as I see google inlines the implementation inside the function body without seperation

**Comment by AshFungor** [comment]
> as I see google inlines the implementation inside the function body without seperation

They inline small functions, do not inline at all, or use public APIs as wrappers for internal functions. Good enough for me :)

**Comment by AshFungor** [comment]
> I think you misunderstood me, not putting the body in the class function body can cause slower compile times because of more things to parse and name lookup.

Yeah, but I can't agree or disagree on that, seems like a minor optimization anyways.

**Comment by AshFungor** [comment]
> I also disagree especially when modules are coming and you can just put the declaration and definition in the same file even for non templated code like normal languages.

I like the idea, just hope it plays out.

**Comment by ZXShady** [comment]
> > as I see google inlines the implementation inside the function body without seperation
> 
> They inline small functions, do not inline at all, or use public APIs as wrappers for internal functions. Good enough for me :)

weird, how is a 4 line function considered small enough to be inlinwd in  body while a 2 liner isn't? this seems inconsistent 

I also mean by inline not "inlining optimizations" or `inline` keyword I mean putting the code of the function inaide the body

**Comment by ZXShady** [comment]
> > I think you misunderstood me, not putting the body in the class function body can cause slower compile times because of more things to parse and name lookup.
> 
> Yeah, but I can't agree or disagree on that, seems like a minor optimization anyways.

I just pointed out that it even has benefits

**Comment by AshFungor** [comment]
> weird, how is a 4 line function considered small enough to be inlinwd in body while a 2 liner isn't? this seems inconsistent

Because you inlined everything?

> I also mean by inline not "inlining optimizations" or inline keyword I mean putting the code of the function inaide the body

I understand that.

> I just pointed out that it even has benefits

Look, I'm not a fan of arguments that lead to nothing. I'm telling you I'm not a fan of this approach and I can tolerate some compromises, clearly not this PR though. So, I'm leaving this to our fellow @HyperWinX, if they want, we merge this, if not, then not.

I prefer to stay out of this.

**Comment by ZXShady** [comment]
> > weird, how is a 4 line function considered small enough to be inlinwd in body while a 2 liner isn't? this seems inconsistent
> 
> Because you inlined everything?


sorry I don't get this, the code is templated some things are defined out of line and some aren't.

> > I just pointed out that it even has benefits
> 
> Look, I'm not a fan of arguments that lead to nothing. I'm telling you I'm not a fan of this approach and I can tolerate some compromises, clearly not this PR though. So, I'm leaving this to our fellow @HyperWinX, if they want, we merge this, if not, then not.
> 
> I prefer to stay out of this.

I just pointed something, no need to get defensive I am completely fine with this not being merged.

the out of line approach has advantages too if you want to support extern templates

**Comment by AshFungor** [comment]
> sorry I don't get this, the code is templated some things are defined out of line and some aren't.

Last time I checked everything was defined out of line :)

Thanks for your time anyways, glad to see someone took interest. Sorry if I was too rude, did not mean that, I see you're smart guy and you definitely have a point here.

**Comment by HyperWinX** [comment]
Hi @ZXShady.

@AshFungor already explained everything, and i fully agree with him. Less lines != more readability. For me its okay to inline really *small* functions, like
```c++
int foo() { return __bar(); }
```
But I'd not inline functions bigger than that. What about compile times? 240 lines is almost nothing, compared to the same STL, where by including one header, you include tons of other (mostly unused lol) headers.

I appreciate the efford you put at it. Thank you.

Rejecting PR.

**Comment by ZXShady** [comment]
> Hi @ZXShady.
> 
> @AshFungor already explained everything, and i fully agree with him. Less lines != more readability. For me its okay to inline really *small* functions, like
> ```c++
> int foo() { return __bar(); }
> ```
> But I'd not inline functions bigger than that. What about compile times? 240 lines is almost nothing, compared to the same STL, where by including one header, you include tons of other (mostly unused lol) headers.
> 
> I appreciate the efford you put at it. Thank you.
> 
> Rejecting PR. 

I would suggest taking the .inl approach then to be conventional.

and compile times weren't really the point it was just something small.


Thank you for considering.

**Pull request closed without merging**
